name: Avalda GitHub Pagesis

on:
  push:
    branches: [main]
    paths-ignore:
      - "data/flights_24h.json"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Laadi hoidla
        uses: actions/checkout@v4
      - name: Seadista GitHub Pages
        uses: actions/configure-pages@v5
      - name: Paki staatiline leht
        uses: actions/upload-pages-artifact@v3
        with:
          path: "."
      - name: Avalda
        id: deployment
        uses: actions/deploy-pages@v4
